# https://kubernetes.io/docs/concepts/workloads/controllers/job/
apiVersion: batch/v1
kind: Job
metadata: 
  name: demo-job-1
  namespace: namespace-1
spec:
  completions: 12
  parallelism: 4
  template:
    metadata:
      name: printing-work
      labels:
        app: batch-task-printing
    spec:
      containers:
        - name: batch-container
          image: busybox
          command: ["sh","-c","ping google.com"]
      restartPolicy: Never
