kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-vol-1
  labels:
    app: node-app
spec: 
  storageClassName: pv-vol-1
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce



