
# B: Builder
FROM python:3.12-slim AS BUILDER
WORKDIR /App

# G: INSTALLAITONS
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/lists/*
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.cargo/bin:${path}"


COPY ./requirements.txt .
RUN uv pip install --system --no-cache -r requirements.txt

COPY . .

# DX: RUNTIME:1
FROM  python:3.12-slim
WORKDIR /App

COPY --from=BUILDER /usr/local /usr/local
COPY --from=BUILDER /App /App

CMD ["python","app.py"]
