kind : Cluster # kind of filw
apiVersion : kind.x-k8s.io/v1alpha4 # check fro ever kind version.
nodes : 
  - role : control-plane # Y: MasterNode => control-plane
    image: kindest/node:v1.34.0
    extraPortMappings :
       - containerPort: 80 # http => port 80
         hostPort: 8080
         protocol: TCP
       - containerPort: 443 # https => port 443
         hostPort: 8443
         protocol: TCP
        # Y: here role, images, and extraPortMappings are in one role obj

  - role : worker 
    image: kindest/node:v1.34.0

  - role : worker
    image: kindest/node:v1.34.0

  - role : worker
    image: kindest/node:v1.34.0
